### ISSUE TITLE
Return banner image to original height (About and Resources pages)

### ISSUE THREAD

**Issue by dayotte** [IMERSS/xetthecum-storymap#10]
Increase banner image height back to original height on About and Resources pages
<img width="871" alt="banners and breadcrumbs" src="https://github.com/user-attachments/assets/b07dee9b-4f0e-404d-946f-f54fd98bf2c9">

**Comment by amb26** [comment]
Solved in https://github.com/IMERSS/xetthecum-storymap/commit/fb4959de235662e3afdfe2bd09b5cfc17f8ab97d
