### ISSUE TITLE
Make capitalisation of page headers consistent throughout 

### ISSUE THREAD

**Issue by dayotte** [IMERSS/xetthecum-storymap#12]
Capilisation of headers is currently inconsistent. Make the following changes:

About page: About the project → About the Project
About page: Project team → Project Team

Landing page: 
- Land acknowledgement → Land Acknowledgement 
- About the project → About the Project 
- Community contributions → Community Contributions

**Comment by amb26** [comment]
Solved in https://github.com/IMERSS/xetthecum-storymap/commit/fb4959de235662e3afdfe2bd09b5cfc17f8ab97d
