### ISSUE TITLE
Update landing page copy to remove the word "Western"

### ISSUE THREAD

**Issue by dayotte** [IMERSS/xetthecum-storymap#16]
In the first section after the Land Acknowledgement, remove the word Western from the phrase "Western ecological science", as it is a problematic framework conceived by colonizers.

This website is the culmination of a cross-cultural, interdisciplinary project that aims to meaningfully braid together Indigenous ways of knowing and ~~Western~~ ecological science to create an ecocultural map of a region known as Xetthecum in the Hul’q’umi’num’ language (Retreat Cove in English), on Galiano Island, BC, Canada. We hope you enjoy exploring this site where you can learn about the local biodiversity, Hul’q’umi’num’ species names, the cultural values of various species and ecological communities, and more.

**Comment by amb26** [comment]
Solved in https://github.com/IMERSS/xetthecum-storymap/commit/fb4959de235662e3afdfe2bd09b5cfc17f8ab97d
