### ISSUE TITLE
High priority: Hul'q'umi'num' audio not appearing on some of the individual species pages

### ISSUE THREAD

**Issue by dayotte** [IMERSS/xetthecum-storymap#30]
Audio that that is available in the biodiversity panels in the storymap is not appearing in some of the individual species pages (under Browse all Species). I noticed this for Salmonberry, Heron, Camas, not sure if it's true for others. @amb26 is there an easy way to cross-check that we have all the audio that is available showing up on the individual species pages?

**Comment by amb26** [comment]
This should be resolved now - I've moved the main site to the same system for resolving audio links as the storymap site and copied across all the audio files
