### ISSUE TITLE
About dropdown is not appearing in nav when in The Story of Xetthecum

### ISSUE THREAD

**Issue by dayotte** [IMERSS/xetthecum-storymap#33]
The About dropdown needs to be added to The Story of Xetthecum page.
![image](https://github.com/user-attachments/assets/6d22312b-1ec7-4001-a82e-be30e6870d0f)

**Comment by amb26** [comment]
Fixed in https://github.com/IMERSS/xetthecum-storymap-story/commit/2ebb52feb552959bfa8131449df020d7f2214d6c
