### ISSUE TITLE
Current page indicator in nav not showing for About or Explore

### ISSUE THREAD

**Issue by dayotte** [IMERSS/xetthecum-storymap#34]
The brown underline bar that indicates the current page should appear when on a sub page of About or Explore (also  when in The Story of Xetthecum). 
![image](https://github.com/user-attachments/assets/6f4791ef-7f74-4c31-b20c-4a31dfca1b46)

**Comment by amb26** [comment]
Is this the same issue as #35 ? Where should the brown underline bar appear?

**Comment by dayotte** [comment]
Not the same issue as 35 - but may have a related problem, which is that there is no parent page, so maybe we can't indicate it in the nav? If you go to the Resources page, you'll see the brown nav bar under Resources in the nav, indicating the current page. That's where it should appear, under Explore, or About, when on any of the subpages.  Also woudl like it to appear when in the Story of Xetthecum.
