### ISSUE TITLE
Breadcrums should include parent nav item

### ISSUE THREAD

**Issue by dayotte** [IMERSS/xetthecum-storymap#35]
When on a subpage of About or Explore the breadcrumbs should include the parent nav item, e.g.:
Home > Explore > Browse all Species, rather than Home > Browse all Species.

![image](https://github.com/user-attachments/assets/a1d60b32-80eb-49f6-9f94-33f5e18bc9f2)

**Comment by amb26** [comment]
An issue with this is that we don't actually have an "explore" page on the site for the breadcrumb level to refer to with a link and so what we get is the "Explore" level of containment seems to fall onto the first subpage instead, "Browse All Species", see if you think this is acceptable ....

**Comment by dayotte** [comment]
@amb26 I know we can't link to the parent page (because there isn't one), but can we just show it in the breadcrumb path? Hope that makes sense.

**Comment by amb26** [comment]
Yes this should now be done, please check over the sites

**Comment by dayotte** [comment]
Thanks @amb26. Can we remove the links to the "parent" page in the breadcrumbs? If I select it it takes me back to the first child page on the drop down list which is confusing. We don't need that to be a link at all. The current page in the breadcrumb is also a link right now (linking to itself). Can we remove that link too? Thanks for adding the current page indicator bars!

**Comment by amb26** [comment]
OK, I have had a go at this. Quarto doesn't let this be configured so I have had to hack it.

**Comment by dayotte** [comment]
Perfect @amb26! Thank you!
