### ISSUE TITLE
Update/fix the layout of the About the Project section on the landing page

### ISSUE THREAD

**Issue by dayotte** [IMERSS/xetthecum-storymap#4]
Priority 2
Update the design of the About the Project section on the landing page according to the mockups. Option 1 if possible, otherwise Option 2. Dana to provide high res image of the map, hopefully @amb26 can provide one.
Option 1:
[
<img width="703" alt="about the project option 1" src="https://github.com/user-attachments/assets/f7afefcc-f9fb-4baf-912e-6aad335c357e">
](url)
Option 2:
<img width="694" alt="about the project option 2" src="https://github.com/user-attachments/assets/d071cb40-15a0-4171-ad3e-14af9e40f9b7">

Figma link (see page - Landing Page Sept 2024): https://www.figma.com/design/yXKyjRyHbnJPB6jrbfO0dq/Xetthecum?node-id=4059-2382&t=BlPJcpGn9NAMxoJY-1

**Comment by jobara** [comment]
High res image provided by @amb26.

![high-res-map-snapshot](https://github.com/user-attachments/assets/f771b089-3ff5-4dc3-afb8-2faf23e0dc28)
