### ISSUE TITLE
Explore/Cultural Values page: make all cards the same size, align the content, and modify design

### ISSUE THREAD

**Issue by dayotte** [IMERSS/xetthecum-storymap#5]
Priority 3
Some of the cards on the Cultural Values page are different sizes, and the cards appear to be interactive when they are not. 
- make all cards the same size/align the cards in the grid
- align internal card content to the top (so headings, text body, images all align vertically from card to card)
- remove drop shadow (this makes it look like the cards are selectable)
- square the corners of the cards (I think this will also help to make them not look like selectable buttons)
- remove all links from images and icons (these are opening the images), but retain links from species names (these link to species cards)
- update the photos (currently blurry) to be the same as the ones used on the linked species pages, crop these to fit to the square format (Dana to provide cropped images)

Alignment should look like this: 
<img width="605" alt="cultural values cards" src="https://github.com/user-attachments/assets/70b80e9b-d758-47ed-9d1b-7d013af5967d">

**Comment by jobara** [comment]
It looks like the current layout is using a flexbox, using a grid layout instead might solve the issue.

**Comment by jobara** [comment]
@dayotte do you have updated images that you'd like to be used?

**Comment by dayotte** [comment]
Thanks @jobara I want to use the same images that are used on the individual species pages linked from those cards. So they'd be the same ones that also appear on the Browse all Species cards. Can you pull from those or do you need me to grab them?

**Comment by dayotte** [comment]
Let's use this image for cascara @jobara 
https://commons.wikimedia.org/wiki/File:Buckthorn_%28Rhamnus_cathartica%29,_fruit_%2819860624419%29.jpg
![Buckthorn_(Rhamnus_cathartica),_fruit_(19860624419)](https://github.com/user-attachments/assets/44a485f3-3efd-4dd0-b6c2-7c2762728184)

**Comment by dayotte** [comment]
Could the  icons and images be aligned regardless of the heading or caption height? I'm seeing this:
![image](https://github.com/user-attachments/assets/cb4a06f1-095f-48bb-8e1b-e6674d477c11)
![image](https://github.com/user-attachments/assets/acd633aa-b6ca-4401-968e-da2f0ea0c287)
![image](https://github.com/user-attachments/assets/72af71af-0b6e-4e7c-9ff2-34970f5bf87e)
