### ISSUE TITLE
Left justify the About the Project and Community Contribution text blocks in mobile view (landing page)

### ISSUE THREAD

**Issue by dayotte** [IMERSS/xetthecum-storymap#6]
In mobile view the About the project and Community contributions text blocks on the landing page are being centred, these should be left-justified.
Currently:
<img width="345" alt="mobile view landing page" src="https://github.com/user-attachments/assets/bba48202-3b38-431d-aba4-8601e46fd8bf">

**Comment by jobara** [comment]
The "About the Project" seems to have been fixed already. Possible with https://github.com/IMERSS/xetthecum-storymap/pull/19
