### ISSUE TITLE
Update layout and add link in Community Contributions section on landing page

### ISSUE THREAD

**Issue by dayotte** [IMERSS/xetthecum-storymap#7]
The layout of the text/image columns in the Community contributions section of the landing page needs updating according to the Figma mockup. In addition, add the external link to iNaturalist back to the bottom of the text block (see mockup). 

Mockup:
<img width="911" alt="community contributions desktop" src="https://github.com/user-attachments/assets/5137d3d3-363e-4db2-a3bc-4f5adc2fc721">
<img width="312" alt="community contributions mobile" src="https://github.com/user-attachments/assets/1127daaf-974d-4260-9976-5cecc42c0e89">

**Comment by amb26** [comment]
Solved in https://github.com/IMERSS/xetthecum-storymap/commit/fb4959de235662e3afdfe2bd09b5cfc17f8ab97d
