### ISSUE TITLE
Add breadcrumbs to the site as shown in mockups

### ISSUE THREAD

**Issue by dayotte** [IMERSS/xetthecum-storymap#8]
Add breadcrumbs to all pages (except for landing page)

<img width="871" alt="banners and breadcrumbs" src="https://github.com/user-attachments/assets/069b8854-585e-46f3-8f10-6d537b58252d">

**Comment by jobara** [comment]
Unfortunately Quarto prepends the breadcrumbs to the title block. Which means that there needs to be a title block, not just an `<h1>` element defined in the markdown file and also that the breadcrumbs will always appear over top of the title.

see: https://github.com/quarto-dev/quarto-cli/blob/main/src/project/types/website/website-navigation.ts#L509-L513

**Comment by jobara** [comment]
> Unfortunately Quarto prepends the breadcrumbs to the title block. Which means that there needs to be a title block, not just an `<h1>` element defined in the markdown file and also that the breadcrumbs will always appear over top of the title.
> 
> see: https://github.com/quarto-dev/quarto-cli/blob/main/src/project/types/website/website-navigation.ts#L509-L513

Looking at the mockups again the breadcrumbs are supposed to be above so that's okay. Will see if I can modify the title block partial to accept a banner and add that above.

**Comment by amb26** [comment]
Justin's researches on how the breadcrumbs are generated: 
https://matrix.to/#/!mDigWuPWilYGiEcOCA:matrix.org/$WVocv-lk9Ryd3C3X-2Ir5ymmod5nWaLRFq3lpdme_B4?via=matrix.org

https://github.com/quarto-dev/quarto-cli/blob/main/src/project/types/website/website-navigation.ts#L509-L513
