### ISSUE TITLE
Add current page indicator bar to the nav

### ISSUE THREAD

**Issue by dayotte** [IMERSS/xetthecum-storymap#9]
Priority 4
Add indicator to show which page is currently active, as per mockup
<img width="618" alt="nav active page indicator" src="https://github.com/user-attachments/assets/41f29b68-99e4-448d-9b3d-5fd0e6087f72">

**Comment by amb26** [comment]
Solved in https://github.com/IMERSS/xetthecum-storymap/commit/fb4959de235662e3afdfe2bd09b5cfc17f8ab97d - needs to be added to "Story" site

**Comment by dayotte** [comment]
Thanks @amb26 , this also needs to be added to the Explore nav item (i.e. when on a subpage of Explore, meaning Browse all Species, Web of Life, Cultural Values or Ecological Communities).
